### PR TITLE
add custom class names support for each option in the options props

### PR DESCRIPTION
**Pull request by razvanip**

### CODE REVIEW

**Comment by razvanip** [comment]
@bvaughn i think it's needed since in some cases u want different styles on options according to business data. Let me know if u think we can merge this today.

**Comment by bvaughn** [comment]
You know you can pass your own [`optionRenderer` prop](https://github.com/bvaughn/react-virtualized-select#custom-option-renderer), right? 😄  If you want custom logic, why not just use it?

**Comment by razvanip** [comment]
I know but it feels i have to write too mutch code using the optionsRenderer!

**Comment by razvanip** [comment]
Is it something that you would consider mergeing?

**Comment by bvaughn** [comment]
You wouldn't lose any styling if you just forked the default option renderer. 😄 

I don't mind merging this feature to make it easier for your use case. I just couldn't drop everything yesterday and make a release because I had work and other things going on. 😄  I suggested the work-around because you seemed to be in a rush, and there was an existing solution you could use without waiting on me.

Check out version 3.1.0.

**Pull request merged**
