### PR TITLE
Revert "Backwards compat bugfix for require('...').default usecase (s…

### PR DESCRIPTION
**Pull request by mbrevda**
…ee issue #57)"

This reverts commit 2b2368a008ec16ae30e101d124a2ccc46612a5ce.

re: https://github.com/bvaughn/react-virtualized-select/issues/57#issuecomment-297737729

### CODE REVIEW

**Comment by bvaughn** [comment]
This won't actually fix the problem you mentioned on #57 will it?

You actually want to revert the change made in PR #56:
```js
module.exports = VirtualizedSelect
```

**Comment by mbrevda** [comment]
So much for trusting git!

**Comment by bvaughn** [comment]
Basically I think the file should go back to what it was before:
```js
export default from './VirtualizedSelect'
```

**Comment by bvaughn** [comment]
Then I/we/someone just needs to figure out how to "fix" the UMD build so the global variable is easier to use.

**Comment by mbrevda** [comment]
Should be better now?

**Comment by bvaughn** [comment]
published to npm as-is. didn't really have time to test.

**Comment by mbrevda** [comment]
Thanks. We can deal with the original issue later

**Pull request merged**
