### PR TITLE
props with defaults does not have to be .isRequired

### PR DESCRIPTION
**Pull request by ShockiTV**

### CODE REVIEW

**Comment by bvaughn** [comment]
The props are still required- it's just that the component will provide a default value if you pass `undefined`.

Essentially there is no impact of tagging the props as `.isRequired`. It just makes the intent of the code a bit clearer, I think?

**Comment by ShockiTV** [comment]
in IDEs it is still throwing warnings cause isRequired props are mandatory...
screen shot 2017-11-21 at 17 34 26

**Comment by bvaughn** [comment]
Huh. Interesting. Is that VS Code? I had no idea it did that.

**Comment by bvaughn** [comment]
Eh, ok. 😄

**Comment by ShockiTV** [comment]
PyCharm, I expect any Jetbrains IDE to behave that way

**Pull request merged**
